filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /log-data/*.log
  exclude_files: [".gz$"]
  multiline:
    pattern: '^\['
    negate: true
    match: after

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"
