version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: java -jar /app-assembly-0.1.0-SNAPSHOT.jar
    volumes:
      - applogs:/var/log
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    command: /start-elasticsearch.sh
    entrypoint: ""
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.4.2
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch
  filebeat:
    container_name: filebeat
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - applogs:/var/lib/mesos/slave/slaves/test-agent/frameworks/test-framework/executors/test-executor/runs/latest
volumes:
  esdata:
    driver: local
  applogs:
    driver: local
