version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: java -jar /app-assembly-0.1.0-SNAPSHOT.jar
    volumes:
      - applogs:/var/log
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    container_name: logstash
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
      - app
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.4.2
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch
  filebeat:
    container_name: filebeat
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    volumes:
      - applogs:/log-data
volumes:
  esdata:
    driver: local
  applogs:
    driver: local
